name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@paulgeorge35'

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Determine version bump
        id: version-bump
        run: |
          # Get the commit messages for the current push
          commits=$(git log --format=%B --merges -n 1)
          
          # Determine version type based on keywords
          if echo "$commits" | grep -iq "BREAKING CHANGE"; then
            echo "major" > version_type
          elif echo "$commits" | grep -iq "feat"; then
            echo "minor" > version_type
          else
            echo "patch" > version_type
          fi
          echo "Version bump determined: $(cat version_type)"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Bump version
        id: bump-version
        run: |
          version_type=$(cat version_type)
          npm version $version_type --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "ci: bump version to $(node -p -e "require('./package.json').version") [skip ci]"
          echo "VERSION=$(node -p -e \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Push updated files
        run: |
          git push origin main
      
      - name: Create and push tag
        run: |
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "$VERSION"
          name: "$VERSION"
          body: |
            ## Changes in this release:
            ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
